spring:
  config:
    import: "classpath:META-INF/build-info.properties"
  application:
    name: jeap-cli
  main:
    banner-mode: console
  banner:
    location: "classpath:banner/cli-banner.txt"

logging:
  pattern:
    console: "%-5level %msg%n"
  level:
    ch.admin.bit.jeap.cli.JeapCLI: warn # Hide Spring Boot startup logs
